apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: nginxhello
  name: single-default-backend-ingress
  annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginxhello
            port:
              number: 80
